# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
addons:
  apt:
    packages:
      - libfftw3-3
      - libfftw3-dev
      - libtiff5-dev
      - libgdal-dev
sudo: false
cache: packages
