# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_mcmc_cpp <- function(args) {
    .Call('_silverblaze_run_mcmc_cpp', PACKAGE = 'silverblaze', args)
}

call_hungarian_cpp <- function(args) {
    .Call('_silverblaze_call_hungarian_cpp', PACKAGE = 'silverblaze', args)
}

